apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
    component: database
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azure-disk
  resources:
    requests:
      storage: 10Gi
